package com.utopiacloud.themyscira.themyscira

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.ResponseBody
import org.springframework.web.bind.annotation.RequestParam

@Controller    // This means that this class is a Controller
@RequestMapping(path = arrayOf("/demo")) // This means URL's start with /demo (after Application path)
class MainController {
    @Autowired // This means to get the bean called userRepository
    private// Which is auto-generated by Spring, we will use it to handle the data
    var userRepository: UserRepository? = null

    // This returns a JSON or XML with the users
    val allUsers: Iterable<User>
        @GetMapping(path = arrayOf("/all"))
        @ResponseBody
        get() = userRepository!!.findAll()

    @GetMapping(path = arrayOf("/add")) // Map ONLY GET Requests
    @ResponseBody
    fun addNewUser(@RequestParam name: String, @RequestParam email: String): String {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        val n = User(
                name = name,
                email = email
        )
        userRepository!!.save(n)
        return "Saved"
    }
}